/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "on-surface": "#2b3437",
        "secondary-fixed-dim": "#d1d4da",
        "primary-fixed": "#d8e2ff",
        "error-container": "#fe8983",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#3c4044",
        "primary-container": "#d8e2ff",
        "primary": "#005bc0",
        "outline": "#737c7f",
        "surface-container": "#eaeff1",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#e0e3e8",
        "inverse-surface": "#0c0f10",
        "on-tertiary-fixed": "#484a4a",
        "on-primary": "#f7f7ff",
        "on-primary-fixed": "#003d85",
        "secondary-container": "#e0e3e8",
        "on-error": "#fff7f6",
        "outline-variant": "#abb3b7",
        "surface-variant": "#dbe4e7",
        "on-primary-container": "#004fa8",
        "on-secondary": "#f6f9fe",
        "on-surface-variant": "#586064",
        "on-error-container": "#752121",
        "secondary-dim": "#505358",
        "primary-dim": "#004fa9",
        "on-tertiary-container": "#5a5c5c",
        "surface-container-low": "#f1f4f6",
        "tertiary-dim": "#525354",
        "on-tertiary-fixed-variant": "#656666",
        "surface-dim": "#d1dce0",
        "primary-fixed-dim": "#c2d4ff",
        "inverse-on-surface": "#9b9d9e",
        "tertiary-fixed-dim": "#e5e5e5",
        "on-background": "#2b3437",
        "surface-tint": "#005bc0",
        "inverse-primary": "#4a8eff",
        "tertiary-container": "#f4f3f3",
        "surface-container-high": "#e3e9ec",
        "tertiary": "#5e5f5f",
        "surface": "#f8f9fa",
        "on-secondary-fixed-variant": "#585c60",
        "on-primary-fixed-variant": "#0058ba",
        "error-dim": "#4e0309",
        "tertiary-fixed": "#f4f3f3",
        "error": "#9f403d",
        "on-secondary-container": "#4e5257",
        "on-tertiary": "#f9f9f9",
        "surface-container-highest": "#dbe4e7",
        "secondary": "#5c5f64"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
